### Vertical Stacking:
#### - It stacks arrays vertically (row-wise).
#### - The arrays must have the same number of columns.

In [3]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.vstack((a, b))
print(result)


[[1 2]
 [3 4]
 [5 6]]


### Horizontal Stacking
#### - It stacks arrays horizontally (column-wise).
#### - The arrays must have the same number of rows.

In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])

result = np.hstack((a, b))
print(result)


[[1 2 5]
 [3 4 6]]
